# Generated by Django 2.0.5 on 2018-05-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_tag',
            name='blog_article_tag',
        ),
    ]
