# Generated by Django 2.0.5 on 2018-05-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_model', '0003_auto_20180508_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='article_blog',
            field=models.ManyToManyField(to='blog_model.article'),
        ),
    ]
