# Generated by Django 2.0.4 on 2018-05-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_model', '0007_auto_20180514_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.CharField(default='pig-1', max_length=255),
        ),
    ]
