# Generated by Django 2.0.5 on 2018-05-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_model', '0008_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='xxx', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='xxx', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='website',
            field=models.CharField(default='xxx', max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
